import { Oxygen } from 'next/font/google';
import './globals.css';
import styles from './generalStyles.module.scss';
import NavBar from '../components/navigation/NavBar';

const oxygen = Oxygen({ weight: '400', subsets: ['latin'] });

export const metadata = {
  title: 'Detect Obesity Level',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={oxygen.className}>
        <NavBar />
        <div className={styles.content}>{children}</div>
      </body>
    </html>
  );
}
